/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "adc.h"
#include "moving_average.h"
#include "calibration.h"
#include "weighing_machine.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define FILTER_SIZE    5U

uint16_t filterBuffer[FILTER_SIZE];
MovingAverageFilter_t filter;

uint16_t raw_adc[100];
uint16_t filtered_adc[100];

Calibration_t calibration;


int main(void)
{
	float value;

	WeighingMachine_Init();

    /* Loop forever */
	for(;;){

        if(Button_IsPressed())
        {
            WeighingMachine_SetZero();
        }

        value = WeighingMachine_GetValue();

	}
}















